apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: labs.alpha.6shore.net
spec:
  group: alpha.6shore.net
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: labs
    singular: lab
    kind: Lab
    shortNames:
    - lab
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            id:
              type: integer
