---
apiVersion: v1
kind: Service
metadata:
  name: kad
  namespace: kadsingle
spec:
  type: NodePort
  selector:
    app: kad
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kad
  namespace: kadsingle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kad
  template:
    metadata:
      labels:
        app: kad
    spec:
      volumes:
      - name: config
        configMap:
          name: kad
          items:
          - key: filecontent
            path: config.yml
      containers:
      - name: app
        image: tomkukral/kad
        command: ["/bin/kad", "--color", "$(COLOR)"]
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_SERVER
          value: localhost:6379
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: kad
              key: color
        volumeMounts:
        # file will be /etc/kad/config.yml
        - name: config
          mountPath: /etc/kad/

