---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kad
spec:                                                                                        
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 63799
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: kad
subsets:
- addresses:
  # c0.k8s.6shore.net
  - ip: 18.198.58.113
  ports:
  - port: 63799
