---
apiVersion: v1
kind: Secret
metadata:
  name: htaccess
  namespace: tekton-pipelines
data:
  ht: Z2xhc3M6JGFwcjEkanZMTUhtREQkSmJUMzU0NEdpWHVXU2UwSVRCbXRBMQoK
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basicauth
  namespace: tekton-pipelines
spec:
  basicAuth:
    secret: htaccess
    removeHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  entryPoints:
  - http
  - https
  routes:
  - kind: Rule

    match: HostRegexp(`tekton.{domain:.+}`)
    priority: 10
    services:
    - name: tekton-dashboard
      port: 9097
    middlewares:
    - name: basicauth
