version: '2'
services:
  web:
    image: tomkukral/kad
    ports:
     - "127.0.0.1:5000:5000"
    environment:
      REDIS_SERVER: "redis:6379"
    depends_on:
     - redis
  redis:
    image: redis
