namespace: argo
bases:
- ../base
resources:                                                                                                                     
- artifact-config.yml
- ingress.yml
- deploy.yml
