---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kad.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "kad.name" . }}
    helm.sh/chart: {{ include "kad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yml: |
    abc: 123
    password: datascript
  color: white
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kad.fullname" . }}-credentials
  labels:
    app.kubernetes.io/name: {{ include "kad.name" . }}
    helm.sh/chart: {{ include "kad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: YWRtaW4=
  password: d29ya3Nob3BTRA==
